### ISSUE TITLE
Security issues are ignored

### ISSUE THREAD

**Issue by JoshuaWise** [RisingStack/nx-compile#4]
I've posted several comments pointing out security issues with nx-compile, and I've pointed at solutions to those problems, but every time, my comments get deleted.

It's clear that the maintainers behind `nx-compile` have no concern for achieving actual security. Rather, they are more interested in their pride.

I'll post it again.

The global object can easily be leaked (even in "version 2.0")
```js
compiler.secure();
var code = compiler.compileCode('return 2..constructor.constructor("return this")()', {});
code(); // => the global object is returned
```

To solve this problem, please take inspiration from my [expression-sandbox](https://github.com/JoshuaWise/expression-sandbox) module.

**Comment by solkimicreb** [comment]
Hi!

I am the only maintainer and I did delete your comments. Security in nx-compile 2.0 is flagged as experimental in the readme and it is under development. 

You decided to go on your own way and try to solve the security issues it has on your own. This is perfectly OK. Howerver instead of forking you decided to **copy** nx-compile and **replace the MIT license with your own one.** Then you posted links to nx-compile about the **copied** nx-compile repo with your fixes and claimed it as your **own work** and tried to **promote it over nx-compile**. After this you called what you did a 'fork'.  It is not a fork and this is not OK.

I am still OK with this if you do not try to promote 'your' work here in every single comment you post. I think you should reconsider your definition of 'fork', 'open source' and 'MIT license'.

P.S.: all your comment outside of this issue will be deleted if you self-promote in them.

**Comment by JoshuaWise** [comment]
All's fair in love and war... but not in software development.

I've converted the [expression-sandbox](https://github.com/JoshuaWise/expression-sandbox) repository into a fork of [nx-compile](https://github.com/RisingStack/nx-compile), to properly portrait its origins, and I've added you to its LICENSE file.

I apologize for that mis-step of mine.

**Comment by JoshuaWise** [comment]
As for the security issue displayed in the first comment, the only way I was able to solve it was by replacing `Function.prototype.constructor` with a proxy. That proxy has an override for `Reflect.apply` and `Reflect.construct`, causing it to only construct proxies of functions. Those proxies are prohibited from returning the global object.

It's a bit messy, but totally secure. I went a bit further with `expression-sandbox`, and converted ANY object/function reachable via primitive prototypes to a proxy. This way, there are no accidentally forgotten loose-ends. It also prevents people from adding their own properties to native functions (for example: `2..toFixed.foo = "bar"`). I'm not sure *how* much security `nx-compile` requires, but I hope these ideas help in securing your sandbox.

**Comment by solkimicreb** [comment]
Great, thx! Sorry for being so harsh and thanks for the warning.

Sadly preventing the the constructor from returning the global object is probably not enough. Overwriting constructors with local variables can still cause unexpected behavior and security leaks in the un-sandboxed code.

I think optimally we should prevent any kind of mutation on objects that come from outside the sandbox while the sandboxed code is executing. I like the Proxy solution you use much more than Object.freeze() since it can be 'turned on and off' with a flag. This way we could prevent mutations only while the sandboxed code is executing and let them happen otherwise.

I will try to check your code in depth tomorrow.

**Comment by solkimicreb** [comment]
Hi!

I am going to close this now an start a fresh discussion for nx-compile 2.0.0 security issues.
